[cosmic-ray]
module-path = "sistemrezervareavion.py"
timeout = 3.0
excluded-modules = []
test-command = "python -m pytest tests/mutation/test_mutation.py -q --tb=short --disable-warnings"

[cosmic-ray.distributor]
name = "local"
workers = 4