[cosmic-ray]
module-path = "sistemrezervareavion.py"
timeout = 10.0
excluded-modules = []
test-command = "python -m pytest tests/mutation/test_mutation.py -q"

[cosmic-ray.distributor]
name = "local"
workers = 4